export const SET_ORDER_LIST = 'ORDER_LIST';
export const ADD_ORDER_LIST = 'ADD_ORDER_LIST';
export const REMOVE_ORDER = 'REMOVE_ORDER';
export const INCREASE_ORDER_COUNT = 'INCREASE_ORDER_COUNT';
export const DECREASE_ORDER_COUNT = 'DECREASE_ORDER_COUNT';